# Generated by Django 2.2.28 on 2023-02-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230218_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sdfbfsd',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
